---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: contour
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes-yml-files
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-source
  validation: client

