---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cp-kafka-connect
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cp-helm-charts
      sourceRef:
        kind: HelmRepository
        name: kafka-community-edition1
      version: 0.6.0
  interval: 10m0s

