---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helmrelease
  namespace: confluentinc
spec:
  chart:
    spec:
      chart: ./charts/cp-control-center
      sourceRef:
        kind: GitRepository
        name: confluentinc
  interval: 10m0s

