---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-community-edition-rel
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cp-helm-charts
      sourceRef:
        kind: HelmRepository
        name: staging
  interval: 30s
  targetNamespace: staging

