---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-staging
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kubernetes-yml-files
      sourceRef:
        kind: GitRepository
        name: app-source
  interval: 30s
  targetNamespace: staging

